In [1]:
from neo4j import GraphDatabase
from dataclasses import dataclass
from collections import defaultdict
from typing import Any

In [2]:
@dataclass
class Attr:
    name: str
    data_type: str
    nullable: bool
        
@dataclass
class FK:
    source_attr_name: str
    target_table: str
    target_attr_name: str

In [3]:
class Node:
    def __init__(self, label, attr, vals):
        self.vals = vals
        self.label = label
        self.attr = attr
        
class Edge:
    def __init__(self, label, source, target, attr=[], vals=[]):
        self.label = label
        self.source = source
        self.target = target
        self.attr = attr
        self.vals = vals

In [4]:
@dataclass(frozen=True)
class Node:
    label: str
    attr: list[str]
    vals: list[Any]
        
@dataclass(frozen=True)
class Edge:
    label: str
    attr: list[str]
    vals: list[Any]
    source: Node
    target: Node

In [5]:
class NodeClass:
    def __init__(self, label, attr, pk, nodes):
        self.label = label
        self.pk = pk
        self.nodes = nodes
        self.attr = attr


class EdgeClass:
    def __init__(self, label, source, target, attr, edges):
        self.label = label
        self.source = source
        self.target = target
        self.attr = attr
        self.edges = edges

In [6]:
class GraphSchema:
    
    def __init__(self, nodes, edges):
        self.nodes = nodes
        self.edges = edges

In [7]:
class Table:
    def __init__(self, name):
        self.name = name
        self.attr = []
        self.fk = []
        self.pk = set()
        self.is_referenced = False
        self.tuples = []
        
    def add_attr(self, attr):
        self.attr.append(attr)
        
    def add_fk(self, source_attribute, target_table_name, target_attribute):
        self.fk.append(FK(source_attribute, target_table_name, target_attribute))
        
    def add_pk(self, attr):
        self.pk.add(attr)
        
    def is_m2m(self):
        if self.is_referenced:
            return False
        
        refcnt = 0
        c = set()
        for fk in self.fk:
            if fk.source_attr_name not in self.pk:
                return False
            if fk.target_table not in c:
                c.add(target_table)
                refcnt += 1
        if refcnt != 2:
            return False
        
        return True
    
    def extract_tables(self):
        if not self.is_m2m():
            raise RuntimeError("exctracting edges is possible only for m2m tables")
            
        targets = []
        for fk in self.fk:
            target_table = fk.target_table
            targets.append(target_table)
            
        return sorted(targets)

In [47]:
TABLE_PRIMARY_KEYS = {
    "suppliers": {'supplier_id'},
    "customer_demographics": {'customer_type_id'},
    "territories": {'territory_id'},
    "shippers": {'shipper_id'},
    "orders": {'order_id'},
    "customer_customer_demo": {'customer_type_id', 'customer_id'},
    "order_details": {'product_id', 'order_id'},
    "employees": {'employee_id'},
    "categories": {'category_id'},
    "employee_territories": {'employee_id', 'territory_id'},
    "customers": {'customer_id'},
    "products": {'product_id'},
    "region": {'region_id'},
    "us_states": {'state_id'}
}

In [9]:
driver = GraphDatabase.driver("neo4j://localhost:7687", auth=("neo4j", "password"))

In [11]:
with driver.session() as session:
    result = session.run("match (n) return n")

In [12]:
uri = "neo4j://localhost:7687"
user = "neo4j"
password = "password"

In [13]:
def nodeMapper(nodeRec):
    label = list(nodeRec.labels)[0]
    attrs = tuple(k for k in nodeRec)
    vals = tuple(nodeRec[k] for k in nodeRec)
    return Node(label, attrs, vals)

In [14]:
def edgeMapper(edgeRec, src, dst):
    label = edgeRec.type
    attrs = tuple(k for k in edgeRec)
    vals = tuple(edgeRec[k] for k in edgeRec)
    return Edge(label, attrs, vals, src, dst)

In [422]:
driver = GraphDatabase.driver(uri, auth=(user, password))
session = driver.session()
result = session.run("match (a)-[b]->(c) return a,b,c")
triplets = []

for s, e, t in result:
    s = nodeMapper(s)
    t = nodeMapper(t)
    e = edgeMapper(e, s, t)
    triplets.append((s, e, t))
    
results2 = session.run("match (a) return a") # merge nodes without edges

In [423]:
tuples = defaultdict(set)

for n1, _, n2 in triplets:
    l = n1.label
    tuples[l].add(n1)
    l = n2.label
    tuples[l].add(n2)

for n1 in results2:
    for n2 in n1:
        s = nodeMapper(n2)
        l = s.label
        tuples[l].add(s)
    
for k in tuples:
    tuples[k] = list(tuples[k])

In [424]:
session.close()

In [425]:
for k in tuples:
    print(k, len(tuples[k]))

territories 53
employees 9
region 4
orders 830
shippers 6
customers 91
products 77
suppliers 29
categories 8
us_states 51

In [426]:
ncs = []
for k, v in tuples.items():
    label = k
    a2t = {}
    for n in v:
        attrs = n.attr
        vals = n.vals
        for i in range(len(attrs)):
            attr = attrs[i]
            tp = type(vals[i])    
            a2t[attr] = tp
    attrs = [Attr(k, a2t[k], False) for k in a2t]
    nc = NodeClass(label, attrs, set(), v)
    ncs.append(nc)

In [427]:
edgesSets = defaultdict(set)

for s, e, t in triplets:
    label = e.label
    edgesSets[label].add(e)

In [428]:
ecs = []

for k, v in edgesSets.items():
    label = k
    a2t = {}
    for e in v:
        attrs = e.attr
        vals = e.vals
        source = e.source.label
        target = e.target.label
        for i in range(len(attrs)):
            attr = attrs[i]
            tp = type(vals[i])
            a2t[attr] = tp
            
    attrs = [Attr(k, a2t[k], False) for k in a2t]
    ec = EdgeClass(label, source, target, attrs, v)
    ecs.append(ec)

In [390]:
for ec in ecs:
    print(ec.label, ec.attr)

employee_territories [Attr(name='territory_id', data_type=<class 'str'>, nullable=False), Attr(name='employee_id', data_type=<class 'int'>, nullable=False)]
region_id []
ship_via []
employee_id []
customer_id []
reports_to []
order_details [Attr(name='discount', data_type=<class 'float'>, nullable=False), Attr(name='quantity', data_type=<class 'int'>, nullable=False), Attr(name='unit_price', data_type=<class 'float'>, nullable=False), Attr(name='order_id', data_type=<class 'int'>, nullable=False), Attr(name='product_id', data_type=<class 'int'>, nullable=False)]
supplier_id []
category_id []

In [79]:
# process primary keys

In [429]:
for nc in ncs:
    keys = TABLE_PRIMARY_KEYS[nc.label]
    nc.pk = keys

In [430]:
def is_m2m(edge_class):
    sources = set()
    targets = set()
    src_many = False
    tgt_many = False
    has_attr = False
    
    for e in edge_class:
        if e.vals:
            has_attr = True
        
        if e.source in sources:
            tgt_many = True
        sources.add(e.source)
        
        if e.target in targets:
            src_many = True
        targets.add(e.target)
        
        
    return src_many, tgt_many, has_attr

In [431]:
for ec in ecs:
    src_many, tgt_many, has_attr = is_m2m(ec.edges)
    if has_attr or (src_many and tgt_many):
        print(generate_migration(ec))
        print("\n\n")

CREATE TABLE employee_territories  (
	territory_id  text,
	employee_id  smallint
);



CREATE TABLE order_details  (
	discount  real,
	quantity  smallint,
	unit_price  real,
	order_id  smallint,
	product_id  smallint
);

In [432]:
def generate_deletion(nc):
    query = f"""DROP TABLE IF EXISTS {nc.label};"""
    
    return query

In [433]:
def generate_migration(nc):
    tablename = nc.label
    query = f"""CREATE TABLE {tablename} """ + " (\n"
    parts = []
    for attr in nc.attr:
        part = ""
        if attr.data_type == float:
            tp = ' real'
        elif attr.data_type == int:
            tp = ' smallint'
        elif attr.data_type == str:
            tp = ' text'
        part += f"\t{attr.name} {tp}"
        if attr.nullable:
            part += " NOT NULL"
        parts.append(part)
        # query += ",\n"
    query += ",\n".join(parts)
    return query + "\n);"

In [434]:
def generate_pk_constraint(nc):
    tablename = nc.label
    pk = list(nc.pk)[0]
    q_tpl = f"ALTER TABLE ONLY {tablename} ADD CONSTRAINT pk_{tablename} PRIMARY KEY ({pk});"
    return q_tpl

In [435]:
def generate_inserts_for_nodeClass(nc):
    
    tpl = "INSERT INTO {} ({}) VALUES ({});"
    res = []
    for node in nc.nodes:
        t = []

        for val in node.vals:
            if isinstance(val, str):
                val = val.replace("'", "''")
                val = "\'" + val + "\'"
            else:
                val = str(val)
            t.append(val)
            
        res.append(tpl.format(node.label, ",".join(node.attr), ",".join(t)))
    return res
        
    return [tpl.format(node.label, ",".join(node.attr), node.vals) for node in nc.nodes]

In [436]:
def generate_inserts_for_edgeClass(ec):
    
    tpl = "INSERT INTO {} ({}) VALUES {};"
        
    return [tpl.format(edge.label, ",".join(edge.attr), edge.vals) for edge in ec.edges]

In [437]:
for nc in ncs:
    print(*generate_inserts_for_nodeClass(nc), sep="\n")

INSERT INTO territories (region_id,territory_description,territory_id) VALUES (1,'Cary','27511');
INSERT INTO territories (region_id,territory_description,territory_id) VALUES (2,'Hoffman Estates','60179');
INSERT INTO territories (region_id,territory_description,territory_id) VALUES (2,'Seattle','98104');
INSERT INTO territories (region_id,territory_description,territory_id) VALUES (1,'Morristown','07960');
INSERT INTO territories (region_id,territory_description,territory_id) VALUES (2,'Santa Clara','95054');
INSERT INTO territories (region_id,territory_description,territory_id) VALUES (3,'Philadelphia','19428');
INSERT INTO territories (region_id,territory_description,territory_id) VALUES (4,'Bentonville','72716');
INSERT INTO territories (region_id,territory_description,territory_id) VALUES (2,'Redmond','98052');
INSERT INTO territories (region_id,territory_description,territory_id) VALUES (1,'Boston','02116');
INSERT INTO territories (region_id,territory_description,territory_id) VALUES (1,'Bedford','01730');
INSERT INTO territories (region_id,territory_description,territory_id) VALUES (2,'Campbell','95008');
INSERT INTO territories (region_id,territory_description,territory_id) VALUES (1,'Rockville','20852');
INSERT INTO territories (region_id,territory_description,territory_id) VALUES (1,'New York','10038');
INSERT INTO territories (region_id,territory_description,territory_id) VALUES (1,'Mellvile','11747');
INSERT INTO territories (region_id,territory_description,territory_id) VALUES (4,'Columbia','29202');
INSERT INTO territories (region_id,territory_description,territory_id) VALUES (1,'Fairport','14450');
INSERT INTO territories (region_id,territory_description,territory_id) VALUES (1,'Edison','08837');
INSERT INTO territories (region_id,territory_description,territory_id) VALUES (3,'Minneapolis','55439');
INSERT INTO territories (region_id,territory_description,territory_id) VALUES (1,'Providence','02903');
INSERT INTO territories (region_id,territory_description,territory_id) VALUES (1,'New York','10019');
INSERT INTO territories (region_id,territory_description,territory_id) VALUES (3,'Racine','53404');
INSERT INTO territories (region_id,territory_description,territory_id) VALUES (4,'Dallas','75234');
INSERT INTO territories (region_id,territory_description,territory_id) VALUES (2,'San Francisco','94105');
INSERT INTO territories (region_id,territory_description,territory_id) VALUES (2,'Phoenix','85014');
INSERT INTO territories (region_id,territory_description,territory_id) VALUES (2,'Bellevue','98004');
INSERT INTO territories (region_id,territory_description,territory_id) VALUES (1,'Braintree','02184');
INSERT INTO territories (region_id,territory_description,territory_id) VALUES (1,'Cambridge','02139');
INSERT INTO territories (region_id,territory_description,territory_id) VALUES (3,'Findlay','45839');
INSERT INTO territories (region_id,territory_description,territory_id) VALUES (3,'Roseville','55113');
INSERT INTO territories (region_id,territory_description,territory_id) VALUES (2,'Santa Monica','90405');
INSERT INTO territories (region_id,territory_description,territory_id) VALUES (4,'Tampa','33607');
INSERT INTO territories (region_id,territory_description,territory_id) VALUES (1,'Louisville','40222');
INSERT INTO territories (region_id,territory_description,territory_id) VALUES (3,'Southfield','48075');
INSERT INTO territories (region_id,territory_description,territory_id) VALUES (2,'Colorado Springs','80909');
INSERT INTO territories (region_id,territory_description,territory_id) VALUES (4,'Atlanta','30346');
INSERT INTO territories (region_id,territory_description,territory_id) VALUES (2,'Chicago','60601');
INSERT INTO territories (region_id,territory_description,territory_id) VALUES (1,'Wilton','06897');
INSERT INTO territories (region_id,territory_description,territory_id) VALUES (2,'Menlo Park','94025');
INSERT INTO territories (region_id,territory_description,territory_id) VALUES (3,'Portsmouth','03801');
INSERT INTO territories (region_id,territory_description,territory_id) VALUES (4,'Savannah','31406');
INSERT INTO territories (region_id,territory_description,territory_id) VALUES (1,'Greensboro','27403');
INSERT INTO territories (region_id,territory_description,territory_id) VALUES (1,'Westboro','01581');
INSERT INTO territories (region_id,territory_description,territory_id) VALUES (3,'Hollis','03049');
INSERT INTO territories (region_id,territory_description,territory_id) VALUES (3,'Bloomfield Hills','48304');
INSERT INTO territories (region_id,territory_description,territory_id) VALUES (3,'Beachwood','44122');
INSERT INTO territories (region_id,territory_description,territory_id) VALUES (4,'Austin','78759');
INSERT INTO territories (region_id,territory_description,territory_id) VALUES (1,'Neward','19713');
INSERT INTO territories (region_id,territory_description,territory_id) VALUES (4,'Orlando','32859');
INSERT INTO territories (region_id,territory_description,territory_id) VALUES (2,'Denver','80202');
INSERT INTO territories (region_id,territory_description,territory_id) VALUES (2,'Santa Cruz','95060');
INSERT INTO territories (region_id,territory_description,territory_id) VALUES (1,'Georgetow','01833');
INSERT INTO territories (region_id,territory_description,territory_id) VALUES (3,'Troy','48084');
INSERT INTO territories (region_id,territory_description,territory_id) VALUES (2,'Scottsdale','85251');
INSERT INTO employees (home_phone,country,extension,notes,address,title_of_courtesy,city,birth_date,last_name,photo,hire_date,title,photo_path,reports_to,employee_id,postal_code,region,first_name) VALUES ('(206) 555-9857','USA','5467','Education includes a BA in psychology from Colorado State University in 1970.  She also completed The Art of the Cold Call.  Nancy is a member of Toastmasters International.','507 - 20th Ave. E.
Apt. 2A','Ms.','Seattle','1948-12-08','Davolio','<memory at 0x126336f40>','1992-05-01','Sales Representative','http://accweb/emmployees/davolio.bmp',2,1,'98122','WA','Nancy');
INSERT INTO employees (home_phone,country,extension,notes,address,title_of_courtesy,city,birth_date,photo,last_name,hire_date,title,photo_path,reports_to,employee_id,region,postal_code,first_name) VALUES ('(206) 555-3412','USA','3355','Janet has a BS degree in chemistry from Boston College (1984).  She has also completed a certificate program in food retailing management.  Janet was hired as a sales associate in 1991 and promoted to sales representative in February 1992.','722 Moss Bay Blvd.','Ms.','Kirkland','1963-08-30','<memory at 0x1265a0280>','Leverling','1992-04-01','Sales Representative','http://accweb/emmployees/leverling.bmp',2,3,'WA','98033','Janet');
INSERT INTO employees (home_phone,country,extension,notes,address,title_of_courtesy,city,birth_date,photo,last_name,hire_date,title,photo_path,reports_to,employee_id,region,postal_code,first_name) VALUES ('(206) 555-8122','USA','5176','Margaret holds a BA in English literature from Concordia College (1958) and an MA from the American Institute of Culinary Arts (1966).  She was assigned to the London office temporarily from July through November 1992.','4110 Old Redmond Rd.','Mrs.','Redmond','1937-09-19','<memory at 0x1265a0400>','Peacock','1993-05-03','Sales Representative','http://accweb/emmployees/peacock.bmp',2,4,'WA','98052','Margaret');
INSERT INTO employees (home_phone,country,extension,notes,address,title_of_courtesy,city,birth_date,photo,last_name,hire_date,title,photo_path,employee_id,region,postal_code,first_name) VALUES ('(206) 555-9482','USA','3457','Andrew received his BTS commercial in 1974 and a Ph.D. in international marketing from the University of Dallas in 1981.  He is fluent in French and Italian and reads German.  He joined the company as a sales representative, was promoted to sales manager in January 1992 and to vice president of sales in March 1993.  Andrew is a member of the Sales Management Roundtable, the Seattle Chamber of Commerce, and the Pacific Rim Importers Association.','908 W. Capital Way','Dr.','Tacoma','1952-02-19','<memory at 0x1265a0100>','Fuller','1992-08-14','Vice President, Sales','http://accweb/emmployees/fuller.bmp',2,'WA','98401','Andrew');
INSERT INTO employees (home_phone,country,extension,notes,address,title_of_courtesy,city,birth_date,last_name,photo,hire_date,title,photo_path,reports_to,employee_id,postal_code,first_name) VALUES ('(71) 555-7773','UK','428','Michael is a graduate of Sussex University (MA, economics, 1983) and the University of California at Los Angeles (MBA, marketing, 1986).  He has also taken the courses Multi-Cultural Selling and Time Management for the Sales Professional.  He is fluent in Japanese and can read and write French, Portuguese, and Spanish.','Coventry House
Miner Rd.','Mr.','London','1963-07-02','Suyama','<memory at 0x1265a0700>','1993-10-17','Sales Representative','http://accweb/emmployees/davolio.bmp',5,6,'EC2 7JR','Michael');
INSERT INTO employees (home_phone,country,extension,notes,address,title_of_courtesy,city,birth_date,photo,last_name,hire_date,title,photo_path,reports_to,employee_id,postal_code,first_name) VALUES ('(71) 555-4444','UK','452','Anne has a BA degree in English from St. Lawrence College.  She is fluent in French and German.','7 Houndstooth Rd.','Ms.','London','1966-01-27','<memory at 0x1265a0b80>','Dodsworth','1994-11-15','Sales Representative','http://accweb/emmployees/davolio.bmp',5,9,'WG2 7LT','Anne');
INSERT INTO employees (home_phone,country,extension,notes,address,title_of_courtesy,city,birth_date,photo,last_name,hire_date,title,photo_path,reports_to,employee_id,region,postal_code,first_name) VALUES ('(206) 555-1189','USA','2344','Laura received a BA in psychology from the University of Washington.  She has also completed a course in business French.  She reads and writes French.','4726 - 11th Ave. N.E.','Ms.','Seattle','1958-01-09','<memory at 0x1265a0a00>','Callahan','1994-03-05','Inside Sales Coordinator','http://accweb/emmployees/davolio.bmp',2,8,'WA','98105','Laura');
INSERT INTO employees (home_phone,country,extension,address,notes,title_of_courtesy,city,birth_date,photo,last_name,hire_date,title,photo_path,reports_to,employee_id,postal_code,first_name) VALUES ('(71) 555-4848','UK','3453','14 Garrett Hill','Steven Buchanan graduated from St. Andrews University, Scotland, with a BSC degree in 1976.  Upon joining the company as a sales representative in 1992, he spent 6 months in an orientation program at the Seattle office and then returned to his permanent post in London.  He was promoted to sales manager in March 1993.  Mr. Buchanan has completed the courses Successful Telemarketing and International Sales Management.  He is fluent in French.','Mr.','London','1955-03-04','<memory at 0x1265a0580>','Buchanan','1993-10-17','Sales Manager','http://accweb/emmployees/buchanan.bmp',2,5,'SW1 8JR','Steven');
INSERT INTO employees (home_phone,country,extension,notes,address,title_of_courtesy,city,birth_date,photo,last_name,hire_date,title,photo_path,employee_id,reports_to,postal_code,first_name) VALUES ('(71) 555-5598','UK','465','Robert King served in the Peace Corps and traveled extensively before completing his degree in English at the University of Michigan in 1992, the year he joined the company.  After completing a course entitled Selling in Europe, he was transferred to the London office in March 1993.','Edgeham Hollow
Winchester Way','Mr.','London','1960-05-29','<memory at 0x1265a0880>','King','1994-01-02','Sales Representative','http://accweb/emmployees/davolio.bmp',7,5,'RG1 9SP','Robert');
INSERT INTO region (region_id,region_description) VALUES (3,'Northern');
INSERT INTO region (region_id,region_description) VALUES (4,'Southern');
INSERT INTO region (region_id,region_description) VALUES (2,'Western');
INSERT INTO region (region_id,region_description) VALUES (1,'Eastern');
INSERT INTO orders (ship_city,ship_postal_code,required_date,freight,order_date,shipped_date,employee_id,ship_via,ship_address,customer_id,ship_name,order_id,ship_country) VALUES ('Luleå','S-958 22','1996-09-09',92.69,'1996-08-12','1996-08-16',8,2,'Berguvsvägen  8','BERGS','Berglunds snabbköp',10278,'Sweden');
INSERT INTO orders (ship_postal_code,ship_city,required_date,freight,order_date,shipped_date,employee_id,ship_via,customer_id,ship_address,ship_name,order_id,ship_country) VALUES ('28001','Madrid','1996-10-14',7.56,'1996-09-16','1996-09-23',1,3,'ROMEY','Gran Vía, 1','Romero y tomillo',10306,'Spain');
INSERT INTO orders (ship_postal_code,ship_city,required_date,freight,ship_region,order_date,shipped_date,employee_id,ship_via,customer_id,ship_address,order_id,ship_name,ship_country) VALUES ('83720','Boise','1997-03-10',86.53,'ID','1997-02-10','1997-02-28',4,2,'SAVEA','187 Suffolk Ln.',10440,'Save-a-lot Markets','USA');
INSERT INTO orders (ship_postal_code,ship_city,required_date,freight,order_date,shipped_date,employee_id,ship_via,customer_id,ship_address,order_id,ship_name,ship_country) VALUES ('01307','Cunewalde','1998-01-01',42.74,'1997-12-04','1997-12-09',3,3,'QUICK','Taucherstraße 10',10765,'QUICK-Stop','Germany');
INSERT INTO orders (ship_postal_code,ship_city,required_date,freight,ship_region,order_date,shipped_date,employee_id,ship_via,customer_id,ship_address,ship_name,order_id,ship_country) VALUES ('97827','Elgin','1997-08-13',45.13,'OR','1997-07-16','1997-07-21',4,1,'HUNGC','City Center Plaza 516 Main St.','Hungry Coyote Import Store',10600,'USA');
INSERT INTO orders (ship_city,ship_postal_code,required_date,freight,ship_region,order_date,shipped_date,employee_id,ship_via,customer_id,ship_address,ship_name,order_id,ship_country) VALUES ('Sao Paulo','05634-030','1997-05-02',46.77,'SP','1997-04-04','1997-04-07',7,2,'TRADH','Av. Inês de Castro, 414','Tradiçao Hipermercados',10496,'Brazil');
INSERT INTO orders (ship_city,ship_postal_code,required_date,freight,ship_region,order_date,shipped_date,employee_id,ship_via,customer_id,ship_address,ship_name,order_id,ship_country) VALUES ('San Cristóbal','5022','1998-05-26',120.92,'Táchira','1998-04-28','1998-05-05',7,2,'HILAA','Carrera 22 con Ave. Carlos Soublette #8-35','HILARION-Abastos',11055,'Venezuela');
INSERT INTO orders (ship_city,ship_postal_code,required_date,freight,ship_region,order_date,shipped_date,employee_id,ship_via,ship_address,customer_id,ship_name,order_id,ship_country) VALUES ('Rio de Janeiro','05454-876','1998-05-12',6.27,'RJ','1998-04-14','1998-05-04',9,2,'Rua do Paço, 67','HANAR','Hanari Carnes',11022,'Brazil');
INSERT INTO orders (ship_postal_code,ship_city,required_date,freight,order_date,shipped_date,employee_id,ship_via,customer_id,ship_address,ship_name,order_id,ship_country) VALUES ('1204','Genève','1997-10-10',232.42,'1997-09-12','1997-09-22',7,2,'RICSU','Starenweg 5','Richter Supermarkt',10666,'Switzerland');
INSERT INTO orders (ship_postal_code,ship_city,required_date,freight,order_date,shipped_date,employee_id,ship_via,customer_id,ship_address,order_id,ship_name,ship_country) VALUES ('05033','México D.F.','1997-05-09',218.15,'1997-04-25','1997-05-05',4,2,'TORTU','Avda. Azteca 123',10518,'Tortuga Restaurante','Mexico');
INSERT INTO orders (ship_city,ship_postal_code,required_date,freight,order_date,shipped_date,employee_id,ship_via,ship_address,customer_id,ship_name,order_id,ship_country) VALUES ('Charleroi','B-6000','1998-04-17',15.55,'1998-03-06','1998-03-18',4,3,'Boulevard Tirou, 255','SUPRD','Suprêmes délices',10930,'Belgium');
INSERT INTO orders (ship_postal_code,ship_city,required_date,freight,order_date,shipped_date,employee_id,ship_via,customer_id,ship_address,order_id,ship_name,ship_country) VALUES ('44000','Nantes','1998-04-21',121.82,'1998-03-24','1998-04-02',2,2,'FRANR','54, rue Royale',10971,'France restauration','France');
INSERT INTO orders (ship_postal_code,ship_city,required_date,freight,order_date,employee_id,ship_via,customer_id,ship_address,ship_name,order_id,ship_country) VALUES ('1010','Buenos Aires','1998-05-11',3.17,'1998-04-13',6,3,'RANCH','Av. del Libertador 900','Rancho grande',11019,'Argentina');
INSERT INTO orders (ship_postal_code,ship_city,required_date,freight,order_date,shipped_date,employee_id,ship_via,customer_id,ship_address,order_id,ship_name,ship_country) VALUES ('42100','Reggio Emilia','1998-01-30',59.78,'1998-01-02','1998-01-12',5,1,'REGGC','Strada Provinciale 124',10812,'Reggiani Caseifici','Italy');
INSERT INTO orders (ship_city,ship_postal_code,required_date,freight,order_date,shipped_date,employee_id,ship_via,customer_id,ship_address,order_id,ship_name,ship_country) VALUES ('London','WX3 6FW','1998-05-12',278.96,'1998-04-28','1998-05-01',8,2,'EASTC','35 King George',11056,'Eastern Connection','UK');
INSERT INTO orders (ship_city,ship_postal_code,required_date,freight,ship_region,order_date,shipped_date,employee_id,ship_via,ship_address,customer_id,ship_name,order_id,ship_country) VALUES ('Sao Paulo','05442-030','1997-02-11',21.48,'SP','1997-01-14','1997-01-17',2,3,'Rua Orós, 92','FAMIA','Familia Arquibaldo',10414,'Brazil');
INSERT INTO orders (ship_city,ship_postal_code,required_date,freight,ship_region,order_date,shipped_date,employee_id,ship_via,ship_address,customer_id,ship_name,order_id,ship_country) VALUES ('Cowes','PO31 7PJ','1996-10-24',41.76,'Isle of Wight','1996-09-26','1996-10-03',4,2,'Garden House Crowther Way','ISLAT','Island Trading',10315,'UK');
INSERT INTO orders (ship_city,ship_postal_code,required_date,freight,ship_region,order_date,shipped_date,employee_id,ship_via,customer_id,ship_address,ship_name,order_id,ship_country) VALUES ('Rio de Janeiro','02389-673','1996-09-24',6.4,'RJ','1996-08-27','1996-09-04',6,2,'QUEDE','Rua da Panificadora, 12','Que Delícia',10291,'Brazil');
INSERT INTO orders (ship_postal_code,ship_city,required_date,freight,ship_region,order_date,shipped_date,employee_id,ship_via,customer_id,ship_address,order_id,ship_name,ship_country) VALUES ('97403','Eugene','1997-08-28',116.53,'OR','1997-07-31','1997-08-05',1,2,'GREAL','2732 Baker Blvd.',10616,'Great Lakes Food Market','USA');
INSERT INTO orders (ship_postal_code,ship_city,required_date,freight,ship_region,order_date,shipped_date,employee_id,ship_via,customer_id,ship_address,ship_name,order_id,ship_country) VALUES ('97827','Elgin','1997-02-12',0.2,'OR','1997-01-15','1997-01-24',3,1,'HUNGC','City Center Plaza 516 Main St.','Hungry Coyote Import Store',10415,'USA');
INSERT INTO orders (ship_postal_code,ship_city,required_date,freight,order_date,shipped_date,employee_id,ship_via,customer_id,ship_address,order_id,ship_name,ship_country) VALUES ('14776','Brandenburg','1998-03-18',77.78,'1998-02-18','1998-02-20',9,2,'KOENE','Maubelstr. 90',10893,'Königlich Essen','Germany');
INSERT INTO orders (ship_postal_code,ship_city,required_date,freight,ship_region,order_date,shipped_date,employee_id,ship_via,customer_id,ship_address,ship_name,order_id,ship_country) VALUES ('97827','Elgin','1997-01-03',20.12,'OR','1996-12-06','1996-12-09',3,2,'HUNGC','City Center Plaza 516 Main St.','Hungry Coyote Import Store',10375,'USA');
INSERT INTO orders (ship_postal_code,ship_city,required_date,freight,order_date,shipped_date,employee_id,ship_via,customer_id,ship_address,order_id,ship_name,ship_country) VALUES ('12209','Berlin','1998-04-27',40.42,'1998-03-16','1998-03-24',1,1,'ALFKI','Obere Str. 57',10952,'Alfred''s Futterkiste','Germany');
INSERT INTO orders (ship_city,ship_postal_code,required_date,freight,ship_region,order_date,shipped_date,employee_id,ship_via,customer_id,ship_address,ship_name,order_id,ship_country) VALUES ('Sao Paulo','05487-020','1997-10-03',105.81,'SP','1997-09-05','1997-09-10',7,2,'QUEEN','Alameda dos Canàrios, 891','Queen Cozinha',10659,'Brazil');

In [438]:
database = "northwind_map"

In [439]:
for nc in ncs:
    print(nc.label, len(nc.nodes))

territories 53
employees 9
region 4
orders 830
shippers 6
customers 91
products 77
suppliers 29
categories 8
us_states 51

In [440]:
with open("/Users/a.palagashvili/coursework/psql/queries/tmp.sql", "w") as out:

    print(f"DROP DATABASE {database};", file=out)
    print(f"CREATE DATABASE {database};", file=out)
    print(f"\c {database};", file=out)
    print("\n\n", file=out)
    
    for nc in ncs:
        deletion = generate_deletion(nc)
        migration = generate_migration(nc)
        print(deletion, file=out)
        print(migration, file=out)
        print("\n\n", file=out)

    for nc in ncs:
        print(*generate_inserts_for_nodeClass(nc), sep='\n', file=out)
        print("\n\n", file=out)

    for nc in ncs:
        print(generate_pk_constraint(nc), file=out)

    print("\n\n", file=out)
    for ec in ecs:
        src_many, tgt_many, has_attr = is_m2m(ec.edges)
        if has_attr or (src_many and tgt_many):
            print(generate_deletion(ec), file=out)
            print(generate_migration(ec), file=out)
            print(*generate_inserts_for_edgeClass(ec), sep="\n", file=out)
            print("\n\n", file=out)

    for ec in ecs:
        src_many, tgt_many, has_attr = is_m2m(ec.edges)
        if not has_attr and (not src_many or not tgt_many):
            if src_many:
                source, target = ec.source, ec.target
                q = f"ALTER TABLE ONLY {source} ADD CONSTRAINT fk_{source}_{target} FOREIGN KEY ({ec.label}) REFERENCES {target};"
                print(q, file=out)
            if tgt_many:
                source, target = ec.source, ec.target
                q = f"ALTER TABLE ONLY {target} ADD CONSTRAINT fk_{target}_{source} FOREIGN KEY ({ec.label}) REFERENCES {source};"
                print(q, file=out)

        else:
            source, target = ec.source, ec.target
            for nc in ncs:
                if nc.label == source:
                    source_nc = nc
            for attr in ec.attr:
                if attr.name in source_nc.pk:
                    source_fk = attr.name

            for nc in ncs:
                if nc.label == target:
                    target_nc = nc
            for attr in ec.attr:
                if attr.name in target_nc.pk:
                    target_fk = attr.name

            q = f"ALTER TABLE ONLY {ec.label} ADD CONSTRAINT pk_{ec.label} PRIMARY KEY ({source_fk}, {target_fk});"
            print(q, file=out)

            q = f"ALTER TABLE ONLY {ec.label} ADD CONSTRAINT fk_{ec.label}_{source} FOREIGN KEY ({source_fk}) REFERENCES {source};"
            print(q, file=out)
            q = f"ALTER TABLE ONLY {ec.label} ADD CONSTRAINT fk_{ec.label}_{target} FOREIGN KEY ({target_fk}) REFERENCES {target};"
            print(q, file=out)

In [ ]:
def generate_fk_contraint_o2m(ec):
    source =

In [204]:
for ec in ecs:
    src_many, tgt_many, has_attr = is_m2m(ec.edges)
    if not has_attr and (not src_many or not tgt_many):
        if src_many:
            source, target = ec.source, ec.target
            q = f"ALTER TABLE ONLY {source} ADD CONSTRAINT fk_{source}_{target} FOREIGN KEY ({ec.label}) REFERENCES {target};"
            print(q)
        if tgt_many:
            source, target = ec.source, ec.target
            q = f"ALTER TABLE ONLY {target} ADD CONSTRAINT fk_{target}_{source} FOREIGN KEY ({ec.label}) REFERENCES {source};"
            print(q)
            
    else:
        source, target = ec.source, ec.target
        for nc in ncs:
            if nc.label == source:
                source_nc = nc
        for attr in ec.attr:
            if attr.name in source_nc.pk:
                source_fk = attr.name
        
        for nc in ncs:
            if nc.label == target:
                target_nc = nc
        for attr in ec.attr:
            if attr.name in target_nc.pk:
                target_fk = attr.name
        
        q = f"ALTER TABLE ONLY {ec.label} ADD CONSTRAINT pk_{ec.label} PRIMARY KEY ({source_fk}, {target_fk});"
        print(q)
        
        q = f"ALTER TABLE ONLY {ec.label} ADD CONSTRAINT fk_{ec.label}_{source} FOREIGN KEY ({source_fk}) REFERENCES {source};"
        print(q)
        q = f"ALTER TABLE ONLY {ec.label} ADD CONSTRAINT fk_{ec.label}_{target} FOREIGN KEY ({target_fk}) REFERENCES {target};"
        print(q)

ALTER TABLE ONLY employee_territories ADD CONSTRAINT pk_employee_territories PRIMARY KEY (territory_id, employee_id);
ALTER TABLE ONLY employee_territories ADD CONSTRAINT fk_employee_territories_territories FOREIGN KEY (territory_id) REFERENCES territories;
ALTER TABLE ONLY employee_territories ADD CONSTRAINT fk_employee_territories_employees FOREIGN KEY (employee_id) REFERENCES employees;
ALTER TABLE ONLY territories ADD CONSTRAINT fk_territories_region FOREIGN KEY (region_id) REFERENCES region;
ALTER TABLE ONLY orders ADD CONSTRAINT fk_orders_shippers FOREIGN KEY (ship_via) REFERENCES shippers;
ALTER TABLE ONLY orders ADD CONSTRAINT fk_orders_employees FOREIGN KEY (employee_id) REFERENCES employees;
ALTER TABLE ONLY orders ADD CONSTRAINT fk_orders_customers FOREIGN KEY (customer_id) REFERENCES customers;
ALTER TABLE ONLY employees ADD CONSTRAINT fk_employees_employees FOREIGN KEY (reports_to) REFERENCES employees;
ALTER TABLE ONLY order_details ADD CONSTRAINT pk_order_details PRIMARY KEY (product_id, order_id);
ALTER TABLE ONLY order_details ADD CONSTRAINT fk_order_details_products FOREIGN KEY (product_id) REFERENCES products;
ALTER TABLE ONLY order_details ADD CONSTRAINT fk_order_details_orders FOREIGN KEY (order_id) REFERENCES orders;
ALTER TABLE ONLY products ADD CONSTRAINT fk_products_suppliers FOREIGN KEY (supplier_id) REFERENCES suppliers;
ALTER TABLE ONLY products ADD CONSTRAINT fk_products_categories FOREIGN KEY (category_id) REFERENCES categories;

In [195]:
source_nc.pk

{'territory_id'}

In [198]:
for attr in ec.attr:
    if attr.name in source_nc.pk:
        source_fk = attr.name

In [199]:
source_fk

'territory_id'

In [191]:
target_nc.label

'employees'

In [186]:
for nc in ncs:
    if nc.label == "employees":
        break

In [188]:
nc.label

'employees'

In [185]:
ec.source, ec.target

('territories', 'employees')

In [143]:
schema = GraphSchema(ncs, [])

In [151]:
# generate migrations for tables

In [133]:
tuples['orders'][0].attr

('ship_postal_code',
 'ship_city',
 'required_date',
 'freight',
 'order_date',
 'shipped_date',
 'employee_id',
 'ship_via',
 'customer_id',
 'ship_address',
 'ship_name',
 'order_id',
 'ship_country')

In [137]:
type(tuples['orders'][0].vals[3]) == float

True

In [66]:
len(t)

108

In [103]:
t[0]

In [100]:
t[0] == t[1]

False

In [94]:
t = []
for k in tuples['employees']:
    if k.vals[-1] == "Andrew":
        if k not in t:
            t.append(k)
            print(k.vals)

['(206) 555-9482', 'USA', '3457', 'Andrew received his BTS commercial in 1974 and a Ph.D. in international marketing from the University of Dallas in 1981.  He is fluent in French and Italian and reads German.  He joined the company as a sales representative, was promoted to sales manager in January 1992 and to vice president of sales in March 1993.  Andrew is a member of the Sales Management Roundtable, the Seattle Chamber of Commerce, and the Pacific Rim Importers Association.', '908 W. Capital Way', 'Dr.', 'Tacoma', '1952-02-19', '<memory at 0x1456b6940>', 'Fuller', '1992-08-14', 'Vice President, Sales', 'http://accweb/emmployees/fuller.bmp', 2, 'WA', '98401', 'Andrew']
['(206) 555-9482', 'USA', '3457', 'Andrew received his BTS commercial in 1974 and a Ph.D. in international marketing from the University of Dallas in 1981.  He is fluent in French and Italian and reads German.  He joined the company as a sales representative, was promoted to sales manager in January 1992 and to vice president of sales in March 1993.  Andrew is a member of the Sales Management Roundtable, the Seattle Chamber of Commerce, and the Pacific Rim Importers Association.', '908 W. Capital Way', 'Dr.', 'Tacoma', '1952-02-19', '<memory at 0x1456b6940>', 'Fuller', '1992-08-14', 'Vice President, Sales', 'http://accweb/emmployees/fuller.bmp', 2, 'WA', '98401', 'Andrew']
['(206) 555-9482', 'USA', '3457', 'Andrew received his BTS commercial in 1974 and a Ph.D. in international marketing from the University of Dallas in 1981.  He is fluent in French and Italian and reads German.  He joined the company as a sales representative, was promoted to sales manager in January 1992 and to vice president of sales in March 1993.  Andrew is a member of the Sales Management Roundtable, the Seattle Chamber of Commerce, and the Pacific Rim Importers Association.', '908 W. Capital Way', 'Dr.', 'Tacoma', '1952-02-19', '<memory at 0x1456b6940>', 'Fuller', '1992-08-14', 'Vice President, Sales', 'http://accweb/emmployees/fuller.bmp', 2, 'WA', '98401', 'Andrew']
['(206) 555-9482', 'USA', '3457', 'Andrew received his BTS commercial in 1974 and a Ph.D. in international marketing from the University of Dallas in 1981.  He is fluent in French and Italian and reads German.  He joined the company as a sales representative, was promoted to sales manager in January 1992 and to vice president of sales in March 1993.  Andrew is a member of the Sales Management Roundtable, the Seattle Chamber of Commerce, and the Pacific Rim Importers Association.', '908 W. Capital Way', 'Dr.', 'Tacoma', '1952-02-19', '<memory at 0x1456b6940>', 'Fuller', '1992-08-14', 'Vice President, Sales', 'http://accweb/emmployees/fuller.bmp', 2, 'WA', '98401', 'Andrew']
['(206) 555-9482', 'USA', '3457', 'Andrew received his BTS commercial in 1974 and a Ph.D. in international marketing from the University of Dallas in 1981.  He is fluent in French and Italian and reads German.  He joined the company as a sales representative, was promoted to sales manager in January 1992 and to vice president of sales in March 1993.  Andrew is a member of the Sales Management Roundtable, the Seattle Chamber of Commerce, and the Pacific Rim Importers Association.', '908 W. Capital Way', 'Dr.', 'Tacoma', '1952-02-19', '<memory at 0x1456b6940>', 'Fuller', '1992-08-14', 'Vice President, Sales', 'http://accweb/emmployees/fuller.bmp', 2, 'WA', '98401', 'Andrew']
['(206) 555-9482', 'USA', '3457', 'Andrew received his BTS commercial in 1974 and a Ph.D. in international marketing from the University of Dallas in 1981.  He is fluent in French and Italian and reads German.  He joined the company as a sales representative, was promoted to sales manager in January 1992 and to vice president of sales in March 1993.  Andrew is a member of the Sales Management Roundtable, the Seattle Chamber of Commerce, and the Pacific Rim Importers Association.', '908 W. Capital Way', 'Dr.', 'Tacoma', '1952-02-19', '<memory at 0x1456b6940>', 'Fuller', '1992-08-14', 'Vice President, Sales', 'http://accweb/emmployees/fuller.bmp', 2, 'WA', '98401', 'Andrew']
['(206) 555-9482', 'USA', '3457', 'Andrew received his BTS commercial in 1974 and a Ph.D. in international marketing from the University of Dallas in 1981.  He is fluent in French and Italian and reads German.  He joined the company as a sales representative, was promoted to sales manager in January 1992 and to vice president of sales in March 1993.  Andrew is a member of the Sales Management Roundtable, the Seattle Chamber of Commerce, and the Pacific Rim Importers Association.', '908 W. Capital Way', 'Dr.', 'Tacoma', '1952-02-19', '<memory at 0x1456b6940>', 'Fuller', '1992-08-14', 'Vice President, Sales', 'http://accweb/emmployees/fuller.bmp', 2, 'WA', '98401', 'Andrew']
['(206) 555-9482', 'USA', '3457', 'Andrew received his BTS commercial in 1974 and a Ph.D. in international marketing from the University of Dallas in 1981.  He is fluent in French and Italian and reads German.  He joined the company as a sales representative, was promoted to sales manager in January 1992 and to vice president of sales in March 1993.  Andrew is a member of the Sales Management Roundtable, the Seattle Chamber of Commerce, and the Pacific Rim Importers Association.', '908 W. Capital Way', 'Dr.', 'Tacoma', '1952-02-19', '<memory at 0x1456b6940>', 'Fuller', '1992-08-14', 'Vice President, Sales', 'http://accweb/emmployees/fuller.bmp', 2, 'WA', '98401', 'Andrew']
['(206) 555-9482', 'USA', '3457', 'Andrew received his BTS commercial in 1974 and a Ph.D. in international marketing from the University of Dallas in 1981.  He is fluent in French and Italian and reads German.  He joined the company as a sales representative, was promoted to sales manager in January 1992 and to vice president of sales in March 1993.  Andrew is a member of the Sales Management Roundtable, the Seattle Chamber of Commerce, and the Pacific Rim Importers Association.', '908 W. Capital Way', 'Dr.', 'Tacoma', '1952-02-19', '<memory at 0x1456b6940>', 'Fuller', '1992-08-14', 'Vice President, Sales', 'http://accweb/emmployees/fuller.bmp', 2, 'WA', '98401', 'Andrew']
['(206) 555-9482', 'USA', '3457', 'Andrew received his BTS commercial in 1974 and a Ph.D. in international marketing from the University of Dallas in 1981.  He is fluent in French and Italian and reads German.  He joined the company as a sales representative, was promoted to sales manager in January 1992 and to vice president of sales in March 1993.  Andrew is a member of the Sales Management Roundtable, the Seattle Chamber of Commerce, and the Pacific Rim Importers Association.', '908 W. Capital Way', 'Dr.', 'Tacoma', '1952-02-19', '<memory at 0x1456b6940>', 'Fuller', '1992-08-14', 'Vice President, Sales', 'http://accweb/emmployees/fuller.bmp', 2, 'WA', '98401', 'Andrew']
['(206) 555-9482', 'USA', '3457', 'Andrew received his BTS commercial in 1974 and a Ph.D. in international marketing from the University of Dallas in 1981.  He is fluent in French and Italian and reads German.  He joined the company as a sales representative, was promoted to sales manager in January 1992 and to vice president of sales in March 1993.  Andrew is a member of the Sales Management Roundtable, the Seattle Chamber of Commerce, and the Pacific Rim Importers Association.', '908 W. Capital Way', 'Dr.', 'Tacoma', '1952-02-19', '<memory at 0x1456b6940>', 'Fuller', '1992-08-14', 'Vice President, Sales', 'http://accweb/emmployees/fuller.bmp', 2, 'WA', '98401', 'Andrew']
['(206) 555-9482', 'USA', '3457', 'Andrew received his BTS commercial in 1974 and a Ph.D. in international marketing from the University of Dallas in 1981.  He is fluent in French and Italian and reads German.  He joined the company as a sales representative, was promoted to sales manager in January 1992 and to vice president of sales in March 1993.  Andrew is a member of the Sales Management Roundtable, the Seattle Chamber of Commerce, and the Pacific Rim Importers Association.', '908 W. Capital Way', 'Dr.', 'Tacoma', '1952-02-19', '<memory at 0x1456b6940>', 'Fuller', '1992-08-14', 'Vice President, Sales', 'http://accweb/emmployees/fuller.bmp', 2, 'WA', '98401', 'Andrew']
['(206) 555-9482', 'USA', '3457', 'Andrew received his BTS commercial in 1974 and a Ph.D. in international marketing from the University of Dallas in 1981.  He is fluent in French and Italian and reads German.  He joined the company as a sales representative, was promoted to sales manager in January 1992 and to vice president of sales in March 1993.  Andrew is a member of the Sales Management Roundtable, the Seattle Chamber of Commerce, and the Pacific Rim Importers Association.', '908 W. Capital Way', 'Dr.', 'Tacoma', '1952-02-19', '<memory at 0x1456b6940>', 'Fuller', '1992-08-14', 'Vice President, Sales', 'http://accweb/emmployees/fuller.bmp', 2, 'WA', '98401', 'Andrew']
['(206) 555-9482', 'USA', '3457', 'Andrew received his BTS commercial in 1974 and a Ph.D. in international marketing from the University of Dallas in 1981.  He is fluent in French and Italian and reads German.  He joined the company as a sales representative, was promoted to sales manager in January 1992 and to vice president of sales in March 1993.  Andrew is a member of the Sales Management Roundtable, the Seattle Chamber of Commerce, and the Pacific Rim Importers Association.', '908 W. Capital Way', 'Dr.', 'Tacoma', '1952-02-19', '<memory at 0x1456b6940>', 'Fuller', '1992-08-14', 'Vice President, Sales', 'http://accweb/emmployees/fuller.bmp', 2, 'WA', '98401', 'Andrew']
['(206) 555-9482', 'USA', '3457', 'Andrew received his BTS commercial in 1974 and a Ph.D. in international marketing from the University of Dallas in 1981.  He is fluent in French and Italian and reads German.  He joined the company as a sales representative, was promoted to sales manager in January 1992 and to vice president of sales in March 1993.  Andrew is a member of the Sales Management Roundtable, the Seattle Chamber of Commerce, and the Pacific Rim Importers Association.', '908 W. Capital Way', 'Dr.', 'Tacoma', '1952-02-19', '<memory at 0x1456b6940>', 'Fuller', '1992-08-14', 'Vice President, Sales', 'http://accweb/emmployees/fuller.bmp', 2, 'WA', '98401', 'Andrew']
['(206) 555-9482', 'USA', '3457', 'Andrew received his BTS commercial in 1974 and a Ph.D. in international marketing from the University of Dallas in 1981.  He is fluent in French and Italian and reads German.  He joined the company as a sales representative, was promoted to sales manager in January 1992 and to vice president of sales in March 1993.  Andrew is a member of the Sales Management Roundtable, the Seattle Chamber of Commerce, and the Pacific Rim Importers Association.', '908 W. Capital Way', 'Dr.', 'Tacoma', '1952-02-19', '<memory at 0x1456b6940>', 'Fuller', '1992-08-14', 'Vice President, Sales', 'http://accweb/emmployees/fuller.bmp', 2, 'WA', '98401', 'Andrew']
['(206) 555-9482', 'USA', '3457', 'Andrew received his BTS commercial in 1974 and a Ph.D. in international marketing from the University of Dallas in 1981.  He is fluent in French and Italian and reads German.  He joined the company as a sales representative, was promoted to sales manager in January 1992 and to vice president of sales in March 1993.  Andrew is a member of the Sales Management Roundtable, the Seattle Chamber of Commerce, and the Pacific Rim Importers Association.', '908 W. Capital Way', 'Dr.', 'Tacoma', '1952-02-19', '<memory at 0x1456b6940>', 'Fuller', '1992-08-14', 'Vice President, Sales', 'http://accweb/emmployees/fuller.bmp', 2, 'WA', '98401', 'Andrew']
['(206) 555-9482', 'USA', '3457', 'Andrew received his BTS commercial in 1974 and a Ph.D. in international marketing from the University of Dallas in 1981.  He is fluent in French and Italian and reads German.  He joined the company as a sales representative, was promoted to sales manager in January 1992 and to vice president of sales in March 1993.  Andrew is a member of the Sales Management Roundtable, the Seattle Chamber of Commerce, and the Pacific Rim Importers Association.', '908 W. Capital Way', 'Dr.', 'Tacoma', '1952-02-19', '<memory at 0x1456b6940>', 'Fuller', '1992-08-14', 'Vice President, Sales', 'http://accweb/emmployees/fuller.bmp', 2, 'WA', '98401', 'Andrew']
['(206) 555-9482', 'USA', '3457', 'Andrew received his BTS commercial in 1974 and a Ph.D. in international marketing from the University of Dallas in 1981.  He is fluent in French and Italian and reads German.  He joined the company as a sales representative, was promoted to sales manager in January 1992 and to vice president of sales in March 1993.  Andrew is a member of the Sales Management Roundtable, the Seattle Chamber of Commerce, and the Pacific Rim Importers Association.', '908 W. Capital Way', 'Dr.', 'Tacoma', '1952-02-19', '<memory at 0x1456b6940>', 'Fuller', '1992-08-14', 'Vice President, Sales', 'http://accweb/emmployees/fuller.bmp', 2, 'WA', '98401', 'Andrew']
['(206) 555-9482', 'USA', '3457', 'Andrew received his BTS commercial in 1974 and a Ph.D. in international marketing from the University of Dallas in 1981.  He is fluent in French and Italian and reads German.  He joined the company as a sales representative, was promoted to sales manager in January 1992 and to vice president of sales in March 1993.  Andrew is a member of the Sales Management Roundtable, the Seattle Chamber of Commerce, and the Pacific Rim Importers Association.', '908 W. Capital Way', 'Dr.', 'Tacoma', '1952-02-19', '<memory at 0x1456b6940>', 'Fuller', '1992-08-14', 'Vice President, Sales', 'http://accweb/emmployees/fuller.bmp', 2, 'WA', '98401', 'Andrew']
['(206) 555-9482', 'USA', '3457', 'Andrew received his BTS commercial in 1974 and a Ph.D. in international marketing from the University of Dallas in 1981.  He is fluent in French and Italian and reads German.  He joined the company as a sales representative, was promoted to sales manager in January 1992 and to vice president of sales in March 1993.  Andrew is a member of the Sales Management Roundtable, the Seattle Chamber of Commerce, and the Pacific Rim Importers Association.', '908 W. Capital Way', 'Dr.', 'Tacoma', '1952-02-19', '<memory at 0x1456b6940>', 'Fuller', '1992-08-14', 'Vice President, Sales', 'http://accweb/emmployees/fuller.bmp', 2, 'WA', '98401', 'Andrew']
['(206) 555-9482', 'USA', '3457', 'Andrew received his BTS commercial in 1974 and a Ph.D. in international marketing from the University of Dallas in 1981.  He is fluent in French and Italian and reads German.  He joined the company as a sales representative, was promoted to sales manager in January 1992 and to vice president of sales in March 1993.  Andrew is a member of the Sales Management Roundtable, the Seattle Chamber of Commerce, and the Pacific Rim Importers Association.', '908 W. Capital Way', 'Dr.', 'Tacoma', '1952-02-19', '<memory at 0x1456b6940>', 'Fuller', '1992-08-14', 'Vice President, Sales', 'http://accweb/emmployees/fuller.bmp', 2, 'WA', '98401', 'Andrew']
['(206) 555-9482', 'USA', '3457', 'Andrew received his BTS commercial in 1974 and a Ph.D. in international marketing from the University of Dallas in 1981.  He is fluent in French and Italian and reads German.  He joined the company as a sales representative, was promoted to sales manager in January 1992 and to vice president of sales in March 1993.  Andrew is a member of the Sales Management Roundtable, the Seattle Chamber of Commerce, and the Pacific Rim Importers Association.', '908 W. Capital Way', 'Dr.', 'Tacoma', '1952-02-19', '<memory at 0x1456b6940>', 'Fuller', '1992-08-14', 'Vice President, Sales', 'http://accweb/emmployees/fuller.bmp', 2, 'WA', '98401', 'Andrew']
['(206) 555-9482', 'USA', '3457', 'Andrew received his BTS commercial in 1974 and a Ph.D. in international marketing from the University of Dallas in 1981.  He is fluent in French and Italian and reads German.  He joined the company as a sales representative, was promoted to sales manager in January 1992 and to vice president of sales in March 1993.  Andrew is a member of the Sales Management Roundtable, the Seattle Chamber of Commerce, and the Pacific Rim Importers Association.', '908 W. Capital Way', 'Dr.', 'Tacoma', '1952-02-19', '<memory at 0x1456b6940>', 'Fuller', '1992-08-14', 'Vice President, Sales', 'http://accweb/emmployees/fuller.bmp', 2, 'WA', '98401', 'Andrew']
['(206) 555-9482', 'USA', '3457', 'Andrew received his BTS commercial in 1974 and a Ph.D. in international marketing from the University of Dallas in 1981.  He is fluent in French and Italian and reads German.  He joined the company as a sales representative, was promoted to sales manager in January 1992 and to vice president of sales in March 1993.  Andrew is a member of the Sales Management Roundtable, the Seattle Chamber of Commerce, and the Pacific Rim Importers Association.', '908 W. Capital Way', 'Dr.', 'Tacoma', '1952-02-19', '<memory at 0x1456b6940>', 'Fuller', '1992-08-14', 'Vice President, Sales', 'http://accweb/emmployees/fuller.bmp', 2, 'WA', '98401', 'Andrew']
['(206) 555-9482', 'USA', '3457', 'Andrew received his BTS commercial in 1974 and a Ph.D. in international marketing from the University of Dallas in 1981.  He is fluent in French and Italian and reads German.  He joined the company as a sales representative, was promoted to sales manager in January 1992 and to vice president of sales in March 1993.  Andrew is a member of the Sales Management Roundtable, the Seattle Chamber of Commerce, and the Pacific Rim Importers Association.', '908 W. Capital Way', 'Dr.', 'Tacoma', '1952-02-19', '<memory at 0x1456b6940>', 'Fuller', '1992-08-14', 'Vice President, Sales', 'http://accweb/emmployees/fuller.bmp', 2, 'WA', '98401', 'Andrew']
['(206) 555-9482', 'USA', '3457', 'Andrew received his BTS commercial in 1974 and a Ph.D. in international marketing from the University of Dallas in 1981.  He is fluent in French and Italian and reads German.  He joined the company as a sales representative, was promoted to sales manager in January 1992 and to vice president of sales in March 1993.  Andrew is a member of the Sales Management Roundtable, the Seattle Chamber of Commerce, and the Pacific Rim Importers Association.', '908 W. Capital Way', 'Dr.', 'Tacoma', '1952-02-19', '<memory at 0x1456b6940>', 'Fuller', '1992-08-14', 'Vice President, Sales', 'http://accweb/emmployees/fuller.bmp', 2, 'WA', '98401', 'Andrew']
['(206) 555-9482', 'USA', '3457', 'Andrew received his BTS commercial in 1974 and a Ph.D. in international marketing from the University of Dallas in 1981.  He is fluent in French and Italian and reads German.  He joined the company as a sales representative, was promoted to sales manager in January 1992 and to vice president of sales in March 1993.  Andrew is a member of the Sales Management Roundtable, the Seattle Chamber of Commerce, and the Pacific Rim Importers Association.', '908 W. Capital Way', 'Dr.', 'Tacoma', '1952-02-19', '<memory at 0x1456b6940>', 'Fuller', '1992-08-14', 'Vice President, Sales', 'http://accweb/emmployees/fuller.bmp', 2, 'WA', '98401', 'Andrew']
['(206) 555-9482', 'USA', '3457', 'Andrew received his BTS commercial in 1974 and a Ph.D. in international marketing from the University of Dallas in 1981.  He is fluent in French and Italian and reads German.  He joined the company as a sales representative, was promoted to sales manager in January 1992 and to vice president of sales in March 1993.  Andrew is a member of the Sales Management Roundtable, the Seattle Chamber of Commerce, and the Pacific Rim Importers Association.', '908 W. Capital Way', 'Dr.', 'Tacoma', '1952-02-19', '<memory at 0x1456b6940>', 'Fuller', '1992-08-14', 'Vice President, Sales', 'http://accweb/emmployees/fuller.bmp', 2, 'WA', '98401', 'Andrew']

In [55]:
len(tuples['employees'])

895

In [13]:
n = triplets[0][0]

In [18]:
n

In [19]:
e = triplets[0][1]

In [28]:
edgeMapper(e)

In [23]:
e.keys()

dict_keys(['territory_id', 'employee_id'])

In [51]:
len(triplets)

16481

In [44]:
node = nodes[0]['n']

In [48]:
list(node.labels)[0]

'suppliers'

In [42]:
node.keys()

['n']

In [34]:
list(result)

[]

In [24]:
result

In [25]:
result = [item for item in result]

In [26]:
result

[]